### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by cocoon** [Lumbridge/CentralLoggingService#4]
Hello, I am glad I found your project here, as I have searched for some time now something like this, a central logging application with a web interface in dotnet. There are so many docker solutions out there or other languages, I was really wondering if I am blind and just search for the wrong things that something basic for central logging was not available.

Is this still beeing worked on? I read that you plan to migrate it for dotnet core.

I had some hickups that I thought I just share here if it helps:

In general the route for Register for example with /api/ was not working, I removed /api/ for most calls currently.

Saving new Alerts did not write the SubscriptionId into the Database for AlertGroups, I just did a workaround for now like this:

```
            var newSub = _uow.Repository<Subscription>().Put(new Subscription
            {
                UserId = userId,
                AlertTriggerGroup = new AlertTriggerGroup
                {
                    UserId = userId,
                    AlertTriggerNodes = nodeList
                },
                AlertTypeId = alertTypeId,
                IsActive = true,
                DateTimeEnabled = DateTime.Now
            });

            

            try
            {
                _uow.Commit();
            }
            catch (Exception ex)
            {
                _ls.Log(StaticData.SeverityType.Error, ex);
                return Json(new { success = false, message = "Failed to save alert." }, JsonRequestBehavior.AllowGet);
            }

            newSub.AlertTriggerGroup.SubscriptionId = newSub.Id;

            try
            {
                _uow.Commit();
            }
            catch (Exception ex)
            {
                _ls.Log(StaticData.SeverityType.Error, ex);
                return Json(new { success = false, message = "Failed to save alert." }, JsonRequestBehavior.AllowGet);
            }
```

In Processor.cs I added just some null checks:

```
uow.Repository<AlertTriggerGroup>().Where(x => x != null && x.Subscription != null && x.Subscription.IsActive && !x.Subscription.IsDeleted).ToList();
```

To be able to register a user I modified UnityConfig.cs (unsure if all is needed)

```
public static void RegisterTypes(IUnityContainer container)
        {
            container.RegisterInstance(new DBEntities());

            container.RegisterType(typeof(IRepository<>), typeof(Repository<>));
            container.RegisterType<IUnitOfWork, UnitOfWork>();
            container.RegisterType<IEntities, DBEntities>();
            container.RegisterType<IController, Controller>();
            container.RegisterType<Controllers.AccountController>(new InjectionConstructor());
            container.Resolve<IUnitOfWork>();
        }
```

**Comment by Lumbridge** [comment]
Hi Cocoon,

I too searched for a system which could deliver the functionality I've put together here but wasn't able to find anything really!

I put this project together in a few days so it hasn't been tested extensively but was definitely getting close to where I wanted it to be. I think I might pick up the project again and migrate it to .NET 6 in the coming days & look at some of the changes you've made.

I appreciate your feedback - I'll close this issue for now 👍🏼
